import {
	type BaseURLCapable,
	Fetcher,
	type TimeoutCapable,
} from "@ahoo-wang/fetcher";
import {
	type ApiMetadata,
	type ApiMetadataCapable,
	api,
	autoGeneratedError,
	body as bodyParam,
	post,
} from "@ahoo-wang/fetcher-decorator";
import type { JsonServerSentEventStream } from "@ahoo-wang/fetcher-eventstream";
import type {
	ChatCompletion,
	ChatCompletionChunk,
	ChatCompletionCreateRequest,
} from "../../../protocol/openai/completions";
import { createStreamResultExtractor } from "../../shared/stream-result-extractor";

const StreamResultExtractor =
	createStreamResultExtractor<ChatCompletionChunk>();

@api()
export class OpenAIChatApi implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@post("chat/completions")
	chatCompletions(
		@bodyParam() request: ChatCompletionCreateRequest,
	): Promise<ChatCompletion> {
		throw autoGeneratedError(request);
	}

	@post("chat/completions", { resultExtractor: StreamResultExtractor })
	streamChatCompletions(
		@bodyParam() request: ChatCompletionCreateRequest,
	): Promise<JsonServerSentEventStream<ChatCompletionChunk>> {
		throw autoGeneratedError(request);
	}
}

export interface OpenAIChatApiOptions extends BaseURLCapable, TimeoutCapable {
	apiKey: string;
}

export function openAIChatApi(options: OpenAIChatApiOptions): OpenAIChatApi {
	const fetcher = new Fetcher({
		baseURL: options.baseURL,
		timeout: options.timeout,
		headers: {
			Authorization: `Bearer ${options.apiKey}`,
		},
	});
	return new OpenAIChatApi({ fetcher });
}
