// src/providers/zhipu/api.ts

import {
	type BaseURLCapable,
	Fetcher,
	type TimeoutCapable,
} from "@ahoo-wang/fetcher";
import {
	type ApiMetadata,
	type ApiMetadataCapable,
	api,
	autoGeneratedError,
	body as bodyParam,
	post,
} from "@ahoo-wang/fetcher-decorator";
import type { JsonServerSentEventStream } from "@ahoo-wang/fetcher-eventstream";
import { createStreamResultExtractor } from "../../shared/stream-result-extractor";
import type {
	ChatCompletionChunk,
	ChatCompletionCreateRequest,
	ChatCompletionResponse,
} from "../protocol/completions";

const StreamResultExtractor =
	createStreamResultExtractor<ChatCompletionChunk>();

@api()
export class ZhipuApi implements ApiMetadataCapable {
	constructor(public readonly apiMetadata?: ApiMetadata) {}

	@post("chat/completions")
	chatCompletions(
		@bodyParam() request: ChatCompletionCreateRequest,
	): Promise<ChatCompletionResponse> {
		throw autoGeneratedError(request);
	}

	@post("chat/completions", { resultExtractor: StreamResultExtractor })
	streamChatCompletions(
		@bodyParam() request: ChatCompletionCreateRequest,
	): Promise<JsonServerSentEventStream<ChatCompletionChunk>> {
		throw autoGeneratedError(request);
	}
}

export interface ZhipuApiOptions extends BaseURLCapable, TimeoutCapable {
	apiKey: string;
}

export function zhipuApi(options: ZhipuApiOptions): ZhipuApi {
	const fetcher = new Fetcher({
		baseURL: options.baseURL,
		timeout: options.timeout,
		headers: {
			Authorization: `Bearer ${options.apiKey}`,
		},
	});
	return new ZhipuApi({ fetcher: fetcher });
}
